FROM node:18.19.1

WORKDIR /app

RUN npm install -g npm@9.2.0 \
    && npm install -g react-native-cli

COPY package.json package-lock.json ./
RUN npm install

COPY . .

EXPOSE 8081

CMD ["npm", "run", "start"]
